/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVenuesRouteImport } from './routes/admin.venues'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketTemplatesRouteImport } from './routes/admin.ticket-templates'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminRefundPoliciesRouteImport } from './routes/admin.refund-policies'
import { Route as AdminPromoCodesRouteImport } from './routes/admin.promo-codes'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminOrganizersRouteImport } from './routes/admin.organizers'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoyaltyRulesRouteImport } from './routes/admin.loyalty-rules'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGovernoratesRouteImport } from './routes/admin.governorates'
import { Route as AdminFeeRulesRouteImport } from './routes/admin.fee-rules'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin.feature-flags'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAudienceRulesRouteImport } from './routes/admin.audience-rules'
import { Route as AdminAdminUsersRouteImport } from './routes/admin.admin-users'
import { Route as AdminVenuesNewRouteImport } from './routes/admin.venues.new'
import { Route as AdminVenuesIdRouteImport } from './routes/admin.venues.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketTemplatesRoute = AdminTicketTemplatesRouteImport.update({
  id: '/ticket-templates',
  path: '/ticket-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundPoliciesRoute = AdminRefundPoliciesRouteImport.update({
  id: '/refund-policies',
  path: '/refund-policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoCodesRoute = AdminPromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizersRoute = AdminOrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRulesRoute = AdminLoyaltyRulesRouteImport.update({
  id: '/loyalty-rules',
  path: '/loyalty-rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGovernoratesRoute = AdminGovernoratesRouteImport.update({
  id: '/governorates',
  path: '/governorates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeeRulesRoute = AdminFeeRulesRouteImport.update({
  id: '/fee-rules',
  path: '/fee-rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudienceRulesRoute = AdminAudienceRulesRouteImport.update({
  id: '/audience-rules',
  path: '/audience-rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVenuesNewRoute = AdminVenuesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminVenuesRoute,
} as any)
const AdminVenuesIdRoute = AdminVenuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVenuesRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/audience-rules': typeof AdminAudienceRulesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/fee-rules': typeof AdminFeeRulesRoute
  '/admin/governorates': typeof AdminGovernoratesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty-rules': typeof AdminLoyaltyRulesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/organizers': typeof AdminOrganizersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/refund-policies': typeof AdminRefundPoliciesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/ticket-templates': typeof AdminTicketTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/venues/$id': typeof AdminVenuesIdRoute
  '/admin/venues/new': typeof AdminVenuesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/audience-rules': typeof AdminAudienceRulesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/fee-rules': typeof AdminFeeRulesRoute
  '/admin/governorates': typeof AdminGovernoratesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty-rules': typeof AdminLoyaltyRulesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/organizers': typeof AdminOrganizersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/refund-policies': typeof AdminRefundPoliciesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/ticket-templates': typeof AdminTicketTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/venues/$id': typeof AdminVenuesIdRoute
  '/admin/venues/new': typeof AdminVenuesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/audience-rules': typeof AdminAudienceRulesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/fee-rules': typeof AdminFeeRulesRoute
  '/admin/governorates': typeof AdminGovernoratesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty-rules': typeof AdminLoyaltyRulesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/organizers': typeof AdminOrganizersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/refund-policies': typeof AdminRefundPoliciesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/ticket-templates': typeof AdminTicketTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/venues/$id': typeof AdminVenuesIdRoute
  '/admin/venues/new': typeof AdminVenuesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/admin-users'
    | '/admin/audience-rules'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/facilities'
    | '/admin/feature-flags'
    | '/admin/fee-rules'
    | '/admin/governorates'
    | '/admin/login'
    | '/admin/loyalty-rules'
    | '/admin/orders'
    | '/admin/organizers'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/promo-codes'
    | '/admin/refund-policies'
    | '/admin/tags'
    | '/admin/ticket-templates'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/'
    | '/admin/events/new'
    | '/admin/orders/$id'
    | '/admin/venues/$id'
    | '/admin/venues/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/admin-users'
    | '/admin/audience-rules'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/facilities'
    | '/admin/feature-flags'
    | '/admin/fee-rules'
    | '/admin/governorates'
    | '/admin/login'
    | '/admin/loyalty-rules'
    | '/admin/orders'
    | '/admin/organizers'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/promo-codes'
    | '/admin/refund-policies'
    | '/admin/tags'
    | '/admin/ticket-templates'
    | '/admin/users'
    | '/admin/venues'
    | '/admin'
    | '/admin/events/new'
    | '/admin/orders/$id'
    | '/admin/venues/$id'
    | '/admin/venues/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/admin-users'
    | '/admin/audience-rules'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/facilities'
    | '/admin/feature-flags'
    | '/admin/fee-rules'
    | '/admin/governorates'
    | '/admin/login'
    | '/admin/loyalty-rules'
    | '/admin/orders'
    | '/admin/organizers'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/promo-codes'
    | '/admin/refund-policies'
    | '/admin/tags'
    | '/admin/ticket-templates'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/'
    | '/admin/events/new'
    | '/admin/orders/$id'
    | '/admin/venues/$id'
    | '/admin/venues/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ticket-templates': {
      id: '/admin/ticket-templates'
      path: '/ticket-templates'
      fullPath: '/admin/ticket-templates'
      preLoaderRoute: typeof AdminTicketTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refund-policies': {
      id: '/admin/refund-policies'
      path: '/refund-policies'
      fullPath: '/admin/refund-policies'
      preLoaderRoute: typeof AdminRefundPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo-codes': {
      id: '/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AdminPromoCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizers': {
      id: '/admin/organizers'
      path: '/organizers'
      fullPath: '/admin/organizers'
      preLoaderRoute: typeof AdminOrganizersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty-rules': {
      id: '/admin/loyalty-rules'
      path: '/loyalty-rules'
      fullPath: '/admin/loyalty-rules'
      preLoaderRoute: typeof AdminLoyaltyRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/governorates': {
      id: '/admin/governorates'
      path: '/governorates'
      fullPath: '/admin/governorates'
      preLoaderRoute: typeof AdminGovernoratesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fee-rules': {
      id: '/admin/fee-rules'
      path: '/fee-rules'
      fullPath: '/admin/fee-rules'
      preLoaderRoute: typeof AdminFeeRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audience-rules': {
      id: '/admin/audience-rules'
      path: '/audience-rules'
      fullPath: '/admin/audience-rules'
      preLoaderRoute: typeof AdminAudienceRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-users': {
      id: '/admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/venues/new': {
      id: '/admin/venues/new'
      path: '/new'
      fullPath: '/admin/venues/new'
      preLoaderRoute: typeof AdminVenuesNewRouteImport
      parentRoute: typeof AdminVenuesRoute
    }
    '/admin/venues/$id': {
      id: '/admin/venues/$id'
      path: '/$id'
      fullPath: '/admin/venues/$id'
      preLoaderRoute: typeof AdminVenuesIdRouteImport
      parentRoute: typeof AdminVenuesRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsNewRoute: typeof AdminEventsNewRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsNewRoute: AdminEventsNewRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminVenuesRouteChildren {
  AdminVenuesIdRoute: typeof AdminVenuesIdRoute
  AdminVenuesNewRoute: typeof AdminVenuesNewRoute
}

const AdminVenuesRouteChildren: AdminVenuesRouteChildren = {
  AdminVenuesIdRoute: AdminVenuesIdRoute,
  AdminVenuesNewRoute: AdminVenuesNewRoute,
}

const AdminVenuesRouteWithChildren = AdminVenuesRoute._addFileChildren(
  AdminVenuesRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAudienceRulesRoute: typeof AdminAudienceRulesRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminFeeRulesRoute: typeof AdminFeeRulesRoute
  AdminGovernoratesRoute: typeof AdminGovernoratesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLoyaltyRulesRoute: typeof AdminLoyaltyRulesRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminOrganizersRoute: typeof AdminOrganizersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPromoCodesRoute: typeof AdminPromoCodesRoute
  AdminRefundPoliciesRoute: typeof AdminRefundPoliciesRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminTicketTemplatesRoute: typeof AdminTicketTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVenuesRoute: typeof AdminVenuesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAudienceRulesRoute: AdminAudienceRulesRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminFeeRulesRoute: AdminFeeRulesRoute,
  AdminGovernoratesRoute: AdminGovernoratesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLoyaltyRulesRoute: AdminLoyaltyRulesRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminOrganizersRoute: AdminOrganizersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPromoCodesRoute: AdminPromoCodesRoute,
  AdminRefundPoliciesRoute: AdminRefundPoliciesRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminTicketTemplatesRoute: AdminTicketTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVenuesRoute: AdminVenuesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
